### ISSUE TITLE
Setting DEFAULT_PALLETE

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/docker-ncwms#3]
I've defined my `docker-compose.yml` file thusly:
```
ncwms:
  image: axiom/docker-ncwms
  ports:
    - "9090:8080"
  container_name: ncwms
  volumes:
    - /opt/docker/ncwms/tomcat/conf/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
    - /opt/docker/ncwms/tomcat/content:/opt/tomcat/.ncWMS2
  environment:
    - DEFAULT_PALETTE=x-Rainbow
```
but my endpoint http://gamone.whoi.edu/ncWMS/Godiva3.html isn't getting that default palette.   The default query from this endpoint looks like this:
```
http://gamone.whoi.edu/ncWMS/wms?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-scalar%2Fdefault&LAYERS=COAWST%2Fh&COLORSCALERANGE=-313%2C6682&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-64.124962239575,25.875037760425,-47.571385416658,42.428614583342&WIDTH=256&HEIGHT=256
```
If I pick the colormap via the Godiva3 gui, the query looks like this:
```
http://gamone.whoi.edu/ncWMS/wms?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-scalar%2Fx-Rainbow&LAYERS=COAWST%2Ftemp&TIME=2016-11-15T00%3A00%3A00.000Z&ELEVATION=-0.96875&COLORSCALERANGE=-0.0144%2C30.65&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-76.877551372721,34.606292091296,-74.729167026319,36.754676437697&WIDTH=256&HEIGHT=256
```

How can I go about debugging this?
